import type { Language, Level, Skill, Week } from '../lib/types'

// Mapa curricular de 26 semanas por idioma, organizado em 6 meses.
// As sequências de inglês e alemão são independentes: cada uma respeita
// as dificuldades da própria língua para falantes de português brasileiro.

export const MONTH_TITLES: Record<number, string> = {
  1: 'Fundamentos',
  2: 'Vida cotidiana',
  3: 'Autonomia em situações comuns',
  4: 'Comunicação mais desenvolvida',
  5: 'Aplicação aos objetivos pessoais',
  6: 'Consolidação e independência',
}

const ALL: Skill[] = ['listening', 'reading', 'writing', 'speaking']
const NO_WRITING: Skill[] = ['listening', 'speaking', 'reading']

function w(
  language: Language,
  number: number,
  month: number,
  level: Level,
  title: string,
  canDo: string,
  grammar: string[],
  vocabulary: string[],
  skills: Skill[] = ALL,
): Week {
  return { id: `${language}-w${String(number).padStart(2, '0')}`, language, number, month, level, title, canDo, grammar, vocabulary, skills }
}

const EN: Week[] = [
  // Mês 1 — Fundamentos
  w('en', 1, 1, 'A1', 'Apresentar-se',
    'Cumprimentar, dizer nome e origem e despedir-se.',
    ['verbo to be (I / you)', 'pronomes sujeito', 'sons /h/ e /θ/', 'alfabeto e soletração'],
    ['cumprimentos e despedidas', 'nome', 'países e nacionalidades'], NO_WRITING),
  w('en', 2, 1, 'A1', 'Dados pessoais',
    'Dar e pedir dados pessoais básicos: idade, telefone, e-mail.',
    ['to be (he / she / it / we / they)', 'perguntas sim/não com to be', 'artigos a / an', 'números 0–100'],
    ['idade', 'telefone e e-mail', 'profissões básicas'], NO_WRITING),
  w('en', 3, 1, 'A1', 'Horas e datas',
    'Perguntar e dizer horas e datas; marcar um encontro simples.',
    ['perguntas com what / where / when / who / how', 'this / that', 'preposições de tempo at / on / in'],
    ['dias da semana', 'meses', 'horas', 'datas']),
  w('en', 4, 1, 'A1', 'Coisas ao redor',
    'Descrever o que há em um lugar e dizer o que você tem.',
    ['there is / there are', 'plural regular e irregular', 'have got / have', 'a / some / any'],
    ['objetos do dia a dia', 'cores', 'sala de aula e escritório']),

  // Mês 2 — Vida cotidiana
  w('en', 5, 2, 'A1', 'Família e pessoas',
    'Apresentar a família e descrever pessoas.',
    ["possessivo 's", 'adjetivos possessivos my / your / his / her / our / their', 'adjetivos de aparência e personalidade'],
    ['família', 'aparência física', 'personalidade']),
  w('en', 6, 2, 'A1', 'Minha rotina',
    'Contar sua rotina e perguntar sobre a de alguém.',
    ['present simple (I / you / we / they)', 'advérbios de frequência', 'perguntas com do'],
    ['verbos de rotina', 'horários', 'partes do dia']),
  w('en', 7, 2, 'A1', 'A rotina dos outros',
    'Falar da rotina de outra pessoa e fazer perguntas sobre ela.',
    ['present simple 3ª pessoa (-s / -es)', 'does / doesn\'t', 'pronúncia de -s final'],
    ['trabalho e estudo', 'atividades de lazer', 'frequência']),
  w('en', 8, 2, 'A1', 'Comida e compras',
    'Pedir uma refeição e fazer compras simples.',
    ['contáveis e incontáveis', 'some / any', 'how much / how many', 'would like'],
    ['alimentos e bebidas', 'restaurante', 'preços e pagamento']),
  w('en', 9, 2, 'A1', 'Casa e agora',
    'Descrever sua casa e dizer o que as pessoas estão fazendo agora.',
    ['preposições de lugar', 'present continuous', 'there is / are (revisão)'],
    ['cômodos e móveis', 'tarefas domésticas', 'ações em andamento']),

  // Mês 3 — Autonomia em situações comuns
  w('en', 10, 3, 'A1', 'Transporte e direções',
    'Pedir e dar direções; comprar uma passagem.',
    ['imperativo', 'can / can\'t (habilidade e permissão)', 'preposições de movimento'],
    ['transportes', 'lugares na cidade', 'direções']),
  w('en', 11, 3, 'A1', 'Viagem e hotel',
    'Fazer uma reserva, resolver o check-in e um problema no quarto.',
    ['would like / I\'d like', 'Can I…? / Could you…?', 'pedidos educados'],
    ['aeroporto', 'hotel', 'reservas e problemas']),
  w('en', 12, 3, 'A2', 'Saúde e ajuda',
    'Descrever um problema de saúde e pedir ajuda.',
    ['should / shouldn\'t', 'must / have to', 'perguntas com how often / how long'],
    ['partes do corpo', 'sintomas', 'farmácia e emergência']),
  w('en', 13, 3, 'A2', 'Resolver problemas',
    'Explicar um problema simples (perda, atraso, reclamação) e pedir uma solução.',
    ['present simple vs present continuous', 'contrações e formas fracas (fala conectada)', 'revisão do mês'],
    ['objetos perdidos', 'atrasos e cancelamentos', 'reclamações educadas']),

  // Mês 4 — Comunicação mais desenvolvida
  w('en', 14, 4, 'A2', 'Ontem',
    'Contar o que fez ontem e no fim de semana.',
    ['was / were', 'past simple regular (-ed)', 'expressões de tempo passado', 'pronúncia de -ed'],
    ['fim de semana', 'atividades passadas', 'expressões de tempo']),
  w('en', 15, 4, 'A2', 'Experiências',
    'Contar uma experiência de viagem e perguntar sobre a de alguém.',
    ['past simple irregular (verbos frequentes)', 'did / didn\'t', 'perguntas no passado'],
    ['viagens', 'verbos irregulares frequentes', 'lugares e eventos']),
  w('en', 16, 4, 'A2', 'Narrar',
    'Narrar uma história curta com começo, meio e fim.',
    ['past continuous', 'when / while', 'sequenciadores first / then / after that / finally'],
    ['histórias e anedotas', 'sentimentos', 'conectores de narrativa']),
  w('en', 17, 4, 'A2', 'Planos e convites',
    'Fazer planos e convites; aceitar e recusar com educação.',
    ['going to', 'will (decisões e previsões)', 'present continuous para o futuro'],
    ['eventos sociais', 'convites', 'expressões de tempo futuro']),
  w('en', 18, 4, 'A2', 'Opiniões e comparações',
    'Dar opinião e comparar opções.',
    ['comparativos', 'superlativos', 'I think / I agree / I disagree', 'too / enough'],
    ['produtos e serviços', 'cidades', 'expressões de opinião']),

  // Mês 5 — Aplicação aos objetivos pessoais
  w('en', 19, 5, 'A2', 'Trabalho e estudos',
    'Falar da sua experiência profissional ou acadêmica.',
    ['present perfect de experiência (Have you ever…?)', 'ever / never', 'apresentação profissional'],
    ['profissões e áreas', 'currículo', 'habilidades']),
  w('en', 20, 5, 'A2', 'E-mails e mensagens',
    'Escrever um e-mail ou mensagem para trabalho ou estudo.',
    ['registro formal e informal', 'phrasal verbs frequentes (set up, find out, pick up, get back)', 'conectores and / but / so / because'],
    ['e-mail e mensagens', 'saudações e fechamentos', 'pedidos e agradecimentos'],
    ['reading', 'writing', 'listening', 'speaking']),
  w('en', 21, 5, 'A2', 'Mudança de país',
    'Lidar com uma situação de mudança: alugar um lugar, abrir conta, documentos.',
    ['quantificadores a lot of / a few / a little / much / many', 'perguntas indiretas simples', 'preposições com documentos'],
    ['moradia', 'banco', 'documentos e burocracia']),
  w('en', 22, 5, 'A2', 'Regras e condições',
    'Explicar regras e condições; negociar algo simples.',
    ['zero conditional', 'first conditional', 'must / mustn\'t / don\'t have to'],
    ['regras', 'acordos', 'consequências']),

  // Mês 6 — Consolidação e independência
  w('en', 23, 6, 'A2', 'Materiais autênticos',
    'Entender a ideia principal de um áudio ou texto autêntico curto.',
    ['variedades britânica e americana', 'fala conectada avançada (linking, redução)', 'estratégias de escuta'],
    ['notícias curtas', 'podcasts', 'avisos e anúncios']),
  w('en', 24, 6, 'B1', 'Manter a conversa',
    'Manter uma conversa de cinco minutos sobre temas conhecidos.',
    ['might / could / may (possibilidade)', 'fillers e perguntas de retorno', 'discordar com educação'],
    ['temas do cotidiano', 'expressões conversacionais', 'opiniões']),
  w('en', 25, 6, 'B1', 'Projeto e revisão',
    'Apresentar-se em um contexto real e revisar seus próprios erros.',
    ['present perfect vs past simple', 'revisão das dificuldades do aluno', 'autocorreção'],
    ['apresentação pessoal', 'revisão geral', 'vocabulário do aluno']),
  w('en', 26, 6, 'B1', 'Avaliação final e continuidade',
    'Realizar tarefas integradas e planejar o estudo independente.',
    ['tarefas integradas', 'estratégias de aprendizagem autônoma', 'plano de 90 dias'],
    ['recursos gratuitos', 'metas', 'rotina de prática']),
]

const DE: Week[] = [
  // Mês 1 — Fundamentos
  w('de', 1, 1, 'A1', 'Sons e cumprimentos',
    'Cumprimentar e dizer nome e origem, escolhendo du ou Sie.',
    ['alfabeto, umlauts (ä ö ü) e ß', 'ich / du / Sie', 'sein (ich bin, du bist, Sie sind)', 'Wie heißt du? / Wie heißen Sie?'],
    ['cumprimentos e despedidas', 'nome', 'países'], NO_WRITING),
  w('de', 2, 1, 'A1', 'Dados pessoais',
    'Dar e pedir dados pessoais básicos.',
    ['números 0–100', 'wohnen / kommen (presente regular)', 'W-Fragen (wie, wo, woher, was)', 'posição do verbo na pergunta'],
    ['idade', 'cidade e país', 'telefone e e-mail'], NO_WRITING),
  w('de', 3, 1, 'A1', 'Gênero, artigos e plural',
    'Nomear objetos com artigo e plural corretos e dizer o que tem.',
    ['der / die / das', 'ein / eine', 'cinco padrões de plural', 'haben'],
    ['objetos do dia a dia (sempre com artigo e plural)', 'cores', 'sala e escritório']),
  w('de', 4, 1, 'A1', 'Horas e datas',
    'Perguntar e dizer horas; marcar um encontro simples.',
    ['Uhrzeit formal e informal', 'Ja/Nein-Fragen', 'posição do verbo (V2)', 'am / um / im'],
    ['Wochentage', 'Monate', 'horas e compromissos']),

  // Mês 2 — Vida cotidiana
  w('de', 5, 2, 'A1', 'Família',
    'Apresentar a família e descrever pessoas.',
    ['Possessivartikel (mein / dein / sein / ihr)', 'Nominativo consolidado', 'adjetivos predicativos'],
    ['família', 'aparência', 'personalidade']),
  w('de', 6, 2, 'A1', 'Rotina',
    'Contar sua rotina e perguntar sobre a de alguém.',
    ['verbos separáveis (aufstehen, anfangen, einkaufen)', 'V2 com Zeitangabe no início', 'presente com mudança de vogal (essen, fahren)'],
    ['verbos de rotina', 'horários', 'partes do dia']),
  w('de', 7, 2, 'A1', 'Comida e compras',
    'Pedir uma refeição e fazer compras simples.',
    ['Akkusativ (den / einen / keinen)', 'nicht vs. kein', 'möchten', 'preços'],
    ['alimentos e bebidas', 'restaurante', 'supermercado e mercado']),
  w('de', 8, 2, 'A1', 'Casa e moradia',
    'Descrever sua casa e dizer onde as coisas estão.',
    ['Dativo (dem / der / dem / den)', 'Wo? + in / an / auf + Dativ', 'es gibt + Akkusativ'],
    ['Zimmer e Möbel (com artigo e plural)', 'moradia', 'posição de objetos']),
  w('de', 9, 2, 'A1', 'Pessoas, lugares e preferências',
    'Descrever pessoas, lugares e o que você gosta de fazer.',
    ['gern / lieber / am liebsten', 'adjetivos predicativos', 'revisão do mês: Nominativo e Akkusativ'],
    ['lazer e hobbies', 'lugares da cidade', 'preferências']),

  // Mês 3 — Autonomia em situações comuns
  w('de', 10, 3, 'A1', 'Transporte e direções',
    'Pedir e dar direções; usar o transporte público.',
    ['Wechselpräpositionen (Wo? Dativ / Wohin? Akkusativ)', 'Imperativ (Sie / du)', 'mit + Dativ'],
    ['transportes', 'lugares na cidade', 'direções']),
  w('de', 11, 3, 'A1', 'Viagem e hotel',
    'Fazer uma reserva e resolver o check-in.',
    ['Modalverben können / wollen / müssen', 'Satzklammer (verbo modal + infinitivo no fim)', 'pedidos educados'],
    ['aeroporto e estação', 'hotel', 'reservas']),
  w('de', 12, 3, 'A2', 'Saúde',
    'Descrever um problema de saúde e marcar uma consulta.',
    ['sollen / dürfen', 'Dativo de pessoa (mir tut … weh)', 'Termin beim Arzt'],
    ['Körperteile (com artigo e plural)', 'sintomas', 'farmácia e emergência']),
  w('de', 13, 3, 'A2', 'Resolver problemas',
    'Explicar um problema simples (perda, atraso, reclamação) e pedir uma solução.',
    ['Perfekt introdução (haben + Partizip regular)', 'revisão Akkusativ / Dativ', 'reclamar com educação'],
    ['objetos perdidos', 'atrasos e cancelamentos', 'reclamações']),

  // Mês 4 — Comunicação mais desenvolvida
  w('de', 14, 4, 'A2', 'Ontem e fim de semana',
    'Contar o que fez ontem e no fim de semana.',
    ['Perfekt com haben e sein', 'Partizip II irregular frequente', 'posição do Partizip no fim'],
    ['fim de semana', 'atividades passadas', 'expressões de tempo']),
  w('de', 15, 4, 'A2', 'Experiências',
    'Contar uma experiência de viagem.',
    ['Präteritum de sein / haben / modais (war, hatte, konnte)', 'Perfekt vs. Präteritum na fala', 'narrar no passado'],
    ['viagens', 'lugares e eventos', 'sentimentos']),
  w('de', 16, 4, 'A2', 'Planos e futuro',
    'Fazer planos e convites; aceitar e recusar.',
    ['Präsens + Zeitangabe para o futuro', 'werden', 'Verben mit Dativ (helfen, gefallen, gehören)'],
    ['eventos sociais', 'convites', 'Termine']),
  w('de', 17, 4, 'A2', 'Opiniões e justificativas',
    'Dar opinião, justificar e comparar.',
    ['weil / dass (verbo no fim)', 'Komparativ / Superlativ', 'ich finde / ich glaube'],
    ['expressões de opinião', 'produtos e cidades', 'argumentos']),
  w('de', 18, 4, 'A2', 'Reflexivos e condições',
    'Falar da rotina pessoal e de planos condicionais.',
    ['verbos reflexivos (sich waschen, sich freuen auf)', 'wenn (condição e tempo)', 'pronomes reflexivos Akk / Dat'],
    ['cuidados pessoais', 'sentimentos', 'condições']),

  // Mês 5 — Aplicação aos objetivos pessoais
  w('de', 19, 5, 'A2', 'Trabalho e estudos',
    'Apresentar-se profissionalmente e fazer pedidos educados.',
    ['Konjunktiv II de cortesia (könnten Sie, ich hätte gern, würden Sie)', 'Lebenslauf', 'apresentação profissional'],
    ['Berufe', 'currículo', 'habilidades']),
  w('de', 20, 5, 'A2', 'E-mails e mensagens',
    'Escrever um e-mail formal e uma mensagem informal.',
    ['Anrede e Grußformel', 'formal vs. informal', 'Nebensätze (revisão weil / dass / wenn)'],
    ['e-mail', 'saudações e fechamentos', 'pedidos e agradecimentos'],
    ['reading', 'writing', 'listening', 'speaking']),
  w('de', 21, 5, 'A2', 'Mudança de país',
    'Lidar com burocracia e busca de moradia.',
    ['Adjektivdeklination introdução (nach dem / ein)', 'Genitiv de reconhecimento', 'perguntas indiretas simples'],
    ['Anmeldung', 'Wohnungssuche', 'Bankkonto e Krankenversicherung']),
  w('de', 22, 5, 'A2', 'Reunião e aula',
    'Participar de uma reunião ou aula simples.',
    ['preposições temporais seit / vor / nach / bis', 'Redemittel de reunião', 'perguntar e confirmar entendimento'],
    ['reunião de trabalho', 'universidade', 'Termine e prazos']),

  // Mês 6 — Consolidação e independência
  w('de', 23, 6, 'A2', 'Materiais autênticos',
    'Entender a ideia principal de um áudio ou texto autêntico curto.',
    ['Umgangssprache vs. Standard', 'estratégias de vocabulário (compostos, prefixos)', 'estratégias de escuta'],
    ['Nachrichten leicht', 'podcasts', 'avisos e anúncios']),
  w('de', 24, 6, 'B1', 'Manter a conversa',
    'Manter uma conversa de cinco minutos sobre temas conhecidos.',
    ['Redemittel para opinar e reagir', 'Rückfragen', 'Adjektivdeklination consolidação'],
    ['temas do cotidiano', 'expressões conversacionais', 'opiniões']),
  w('de', 25, 6, 'B1', 'Projeto e revisão',
    'Apresentar-se em um contexto real e revisar seus próprios erros.',
    ['casos (Nom / Akk / Dat) revisão', 'posição do verbo revisão', 'Perfekt vs. Präteritum'],
    ['apresentação pessoal', 'revisão geral', 'vocabulário do aluno']),
  w('de', 26, 6, 'B1', 'Avaliação final e continuidade',
    'Realizar tarefas integradas e planejar o estudo independente.',
    ['tarefas integradas (Gespräch, Anweisungen, Nachricht, Alltagssituation)', 'autocorreção de casos e posição do verbo', 'estratégias de aprendizagem autônoma', 'plano de 90 dias'],
    ['recursos gratuitos', 'metas', 'rotina de prática']),
]

export const CURRICULUM: Week[] = [...EN, ...DE]

export function weeksFor(language: Language): Week[] {
  return CURRICULUM.filter((w) => w.language === language)
}

export function weeksForMonth(language: Language, month: number): Week[] {
  return weeksFor(language).filter((w) => w.month === month)
}
